// Module included in the following assemblies:
//
// assembly-todo.adoc

[id='proc-manual-restart-kafka-{context}']
= Manually restart a Kafka cluster

This procedure describes how to manually restart an existing Kafka cluster by using an {ProductPlatformName} annotation.

.Prerequisites

* A running Kafka cluster.
* A running Cluster Operator.

.Procedure

. Find the name of `StatefulSet` which controls Kafka pods to restart.
+
Lets say the cluser is named _my-cluster_. The name of the Kafka StatefulSet is _my-cluster-kafka_.
+

. Annotate `StatefulSet` resource in {ProductPlatformName}.
+
ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl annotate statefulset _cluster-name_-kafka cluster.operator.strimzi.io/manual-rolling-update=true
endif::Kubernetes[]
+
On {OpenShiftName} this can be done using `oc annotate`:
[source,shell,subs=+quotes]
oc annotate statefulset _cluster-name_-kafka cluster.operator.strimzi.io/manual-rolling-update=true
+
. Wait for next reconciliation and for all pods in annotated `StatefulSet` rolling update will be done.
After all pods are restarted the annotation is removed from `StatefulSet`.


.Additional resources

* For more information about deploying the Cluster Operator, see xref:cluster-operator-str[].
* For more information about deploying the Kafka cluster, see xref:deploying-kafka-cluster-openshift-str[] and xref:deploying-kafka-cluster-kubernetes-str[].
