---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-topic-operator-delegation
  labels:
    app: {{ template "strimzi.name" . }}
    chart: {{ template "strimzi.chart" . }}
    component: topic-operator-role-binding
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: strimzi-topic-operator
  apiGroup: rbac.authorization.k8s.io
{{- $root := . -}}
{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-topic-operator-delegation
  labels:
    app: {{ template "strimzi.name" $root }}
    chart: {{ template "strimzi.chart" $root }}
    component: topic-operator-role-binding
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: {{ . }}
roleRef:
  kind: ClusterRole
  name: strimzi-topic-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
